### ISSUE TITLE
UIに関する改善

### ISSUE THREAD

**Issue by vrctaki** [vrctaki/VRChatOptionalBoot#4]
1. フォントのメリハリをつける
2. グループの見直し
3. 読みやすいように表示を広めに余白を取る
4. キャプションバーのアイコンに指定のアイコンを使用する(*1)

*1 `$window.Icon = ".\vrchat_optional_boot.ico"`

**Comment by naqtn** [comment]
![image](https://user-images.githubusercontent.com/11162845/81239735-9fb57f00-9040-11ea-80c4-fe4dcb44c16f.png)
こんな感じにヘッダ画像入れるのはどうでしょう？やりすぎでしょうか？（画像は例として）

なお XAML 記述の中にカレントパス相対パスリソースは書けないっぽいので、こうしました：
`
    <Image Source="PSScriptRoot/backimage2.png" MaxHeight="100" />
`
`
[xml]$xaml = (Get-Content ".\main.xaml") -replace "PSScriptRoot", $PSScriptRoot
`
（相対パスはデフォルトでは powershell.exe のアセンブリからの相対で解釈される？ https://social.technet.microsoft.com/Forums/en-US/e40fead1-8861-4551-a8a2-857490b0418c/use-relative-path-in-xamlfile-handled-by-powershell?forum=winserverpowershell ）

**Comment by vrctaki** [comment]
画像や背景色は付いていた方が見やすいですね。
ありがとうございます。追加します。

5. ヘッダ画像の追加
6. 背景色など、色情報を追加

**Comment by vrctaki** [comment]
@naqtn ヘッダの件、ありがとうございました。
全体的にUIを見直して、v0.0.9で取り込みました。
