### ISSUE TITLE
VRChat の launch.bat からワールド指定 URL を受け取れるようにする

### ISSUE THREAD

**Issue by naqtn** [vrctaki/VRChatOptionalBoot#5]
VRChat.exe と同じところにある launch.bat は、ブラウザから vrchat: プロトコルのリンクを開いた時に実行され、第二引数にその URL が引き渡されます。それを受け取ってこのツールを起動できるようにすれば、ブラウザからの起動で VR/Desktop が選べるようになります。（SDK で VRChat.exe を指定していない場合の Test 起動でもこれが使われます。）

どうでしょうか。

必要と思われる変更：
* インストール時に launch.bat を書き換え、このツールを URL と共に起動するようにする。
* （お行儀よくするには置き換え前にコピーを取っておく）
* ツールは、この引数があったらそれを入力済みのように扱う。具体的には：
    * 何らかの形で指定された情報を表示する
    * 通常の world ID 入力欄、アクセシビリティ指定欄は操作不能にする。（置き換えることに意味は無いのと操作ミスを防ぐための意味で）
    * VRChat 起動時に URL を組み立てるのではなく、指定されたものを使うようにする

**Comment by vrctaki** [comment]
どう含めるかについては考えるとして、実装方法として、
launch.bat が vrchat_optional_boot.ps1 を利用する場合の最低限の修正内容。

* launch.bat の書き換え内容<br />
   ```batch
   cd /d %1
   powershell -ExecutionPolicy RemoteSigned .\vrchat_optional_boot.ps1 ""%2""
   ```
* vrchat_optional_boot.ps1<br />
   ```powershell
   Param(
       [string]$LaunchURL  # この行を追加
       [switch]$CreateShortcut
   )
   # ...(中略)
       if ($LaunchURL -ne $null) {  # この if 文のブロックを追加
           $room_url = $LaunchURL 
           $boot_properties += $room_url
       }
       elseif ($txt_worldID.Text.Length -and $txt_worldID.Text -match $regex_worldID) {  # if から elseif に変更
           $dammy_user = "usr_00000000-0000-0000-0000-000000000000"
   ```
* 他、world_id の入力領域については、途中 `$txt_worldID.IsEnabled = $false` を含める。

上記変更についてはローカルテストは未考慮です。

**Comment by naqtn** [comment]
launch.bat の方ですが、 %1 は VRChat.exe の場所を指すのでこれでは動きません。cd 先はショートカットがしているのと同様に VRChatOptionalBoot を配置した場所で、そのように展開したバッチファイルにする必要があるかと思います。

 （vrchat_optional_boot.ps1 をそこに入れるというのなら別ですが、今は別途の場所に置く設計ですよね（？））

ちなみにこの「VRChat.exe の場所」の情報はレジストリ HKEY_CLASSES_ROOT\VRChat\shell\open\command に直接に書かれています。（そこに、launch.bat を起動するように書いてある）

**Comment by vrctaki** [comment]
launch.bat と同階層に置くつもりでしたが、不用意にファイルは設置しない方が良いので指定は変更した方が良さそうですね。

**Comment by vrctaki** [comment]
> ちなみにこの「VRChat.exe の場所」の情報はレジストリ HKEY_CLASSES_ROOT\VRChat\shell\open\command に直接に書かれています。（そこに、launch.bat を起動するように書いてある）

HKEY_CLASSES_ROOT はシステム用の設定とユーザ個別の設定の両方が反映されるようですね。
* Windows レジストリ 解剖記: HKEY_CLASSES_ROOT - Programming Field
  https://www.pg-fl.jp/program/winreg/classes.htm
> このキーはHKEY_LOCAL_MACHINE\Software\ClassesとHKEY_CURRENT_USER\Software\Classesを組み合わせた内容で、直接 HKEY_CLASSES_ROOT にキーや値を登録した場合は HKEY_LOCAL_MACHINE\Software\Classes 以下に登録したものと見なされます。

今回は個人用の設定としたいため、レジストリキー `コンピューター\HKEY_CURRENT_USER\Software\Classes\VRChat\shell\open\command` を使おうと考えています。
ここに Optional Boot のスクリプトを指定する事で、ブラウザからOptional Bootを直接起動できました(以下、指定の例)
```powershell
powershell -ExecutionPolicy RemoteSigned "C:\Users\xxxx\Documents\ツール\VRCOptionalBoot\vrchat_optional_boot.ps1" '"%1"'
```

機能の有効化については、Optional Bootのメニューから選べるようにすれば構成もシンプルに保てそうです。

**Comment by vrctaki** [comment]
ブラウザ起動モードをサポートしました a2608a1dd11c0d8a3ea9572c709ae19f7566af1e
[menu]>[Set boot this from browser launch.]

![image](https://user-images.githubusercontent.com/60001124/85929627-79e68100-b8f1-11ea-91ea-ec47fa6cf092.png)

> 通常の world ID 入力欄、アクセシビリティ指定欄は操作不能にする。（置き換えることに意味は無いのと操作ミスを防ぐための意味で）

操作ミスは発生しづらいように感じましたので、今回のアップデートでは見送りました。
誤操作が起こりやすいようであれば追加します。

**Comment by vrctaki** [comment]
user_idを取得していなかったため、フレンドの居るワールドに入れない不具合がありました。
ブラウザ起動時にworld_idやアクセシビリティの変更をオフにする設定を入れつつ、ユーザIDを取得する修正を入れます。

**Comment by vrctaki** [comment]
5c28988300ba9cc3b719e0bff4aa90569d29458c にて修正済みです。

**Comment by vrctaki** [comment]
このissueで取り扱っていた内容は実装済みで、使ってみて他に不具合もなさそうなので一度クローズします。
